// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"database/sql"
)

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Note struct {
	ID         int32          `json:"id"`
	CategoryID sql.NullInt32  `json:"category_id"`
	Title      string         `json:"title"`
	Content    sql.NullString `json:"content"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}
